const images = {
   "ax" : {
      "name" : 'the Åland Islands',
      "original" : 'Original name : Åland',
      "capital" : 'Capital : Mariehamn',
      "languages": 'Official languages : Swedish',
      "population":  'Population : 30,129',
      "call" : 'Calling code : +358 18',
      "internet": 'Internet TLD : .ax',
   },
   "dk" : {
      "name" : 'Denmark',
      "original" : 'Original name : Danmark',
      "capital" : 'Capital : Copenhagen',
      "languages": 'Official languages : Danish',
      "population":  'Population : 5,873,420',
      "call" : 'Calling code : +45',
      "internet": 'Internet TLD : .dk',
   },
   "fi" : {
      "name" : 'Finland',
      "original" : 'Original name : Suomen tasavalta',
      "capital" : 'Capital : Helsinki',
      "languages": 'Official languages : Finnish, Swedish',
      "population":  'Population : 5,553,000',
      "call" : 'Calling code : +358',
      "internet": 'Internet TLD : .fi',
      },
   "fo": {
         "name" : 'Faroe Islands',
         "original" : 'Original name : Føroyar',
         "capital" : 'Capital : Tórshavn',
         "languages": 'Official languages : Faroese, Danish',
         "population":  'Population : 53,882',
         "call" : 'Calling code : +298',
         "internet": 'Internet TLD : .fo',
      },
   "gl": {
         "name" : 'Greenland',
         "original" : 'Original name : Kalaallit Nunaat',
         "capital" : 'Capital : Nuuk',
         "languages": 'Official languages : Greenlandic',
         "population":  'Population : 56,081',
         "call" : 'Calling code : +299',
         "internet": 'Internet TLD : .gl',
      },
   "is": {
         "name" : 'Iceland',
         "original" : 'Original name : Ísland',
         "capital" : 'Capital : Reykjavík',
         "languages": 'Official languages : Icelandic',
         "population":  'Population : 371,580',
         "call" : 'Calling code : +354',
         "internet": 'Internet TLD : .is',
      },
      "no": {
         "name" : 'Norway',
         "original" : 'Original name : Norge',
         "capital" : 'Capital : Oslo',
         "languages": 'Official languages : Norwegian, Sámi',
         "population":  'Population : 5,425,270',
         "call" : 'Calling code : +47',
         "internet": 'Internet TLD : .no',
      },
      "se": {
         "name" : 'Sweden',
         "original" : 'Original name : Sverige',
         "capital" : 'Capital : Stockholm',
         "languages": 'Official languages : Swedish',
         "population":  'Population : 10,402,070',
         "call" : 'Calling code : +46',
         "internet": 'Internet TLD : .se',
      }
}
